
version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    container_name: capitalflow_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: capitalflow
      POSTGRES_PASSWORD: capitalflow_password
      POSTGRES_DB: capitalflow
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U capitalflow"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Next.js Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: capitalflow_app
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgresql://capitalflow:capitalflow_password@db:5432/capitalflow"
      NEXTAUTH_URL: "http://localhost:3000"
      NEXTAUTH_SECRET: "your-super-secret-jwt-secret-key-here"
      NODE_ENV: "production"
    ports:
      - "3000:3000"
    volumes:
      - ./app/.env:/app/.env
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis (Optional - for caching and session storage)
  redis:
    image: redis:7-alpine
    container_name: capitalflow_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

volumes:
  postgres_data:
  redis_data:

networks:
  default:
    name: capitalflow_network
